<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since	 1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
get_header(); ?>

<?php do_action( 'response_before_container'); ?>

<div id="container" class="container-fluid">
	<div class="row-fluid">
		
		<div id="content" class="span12">
			
			<?php do_action( 'response_before_content'); ?>
	
			<article id="post-0" class="post error404 not-found">
				<header class="entry-header">
					<h1 class="entry-title"><?php _e( 'Oops! That page can&rsquo;t be found.', 'response' ); ?></h1>
				</header>
	
				<div class="entry-content">
					<p><?php _e( 'It looks like nothing was found at this location. Maybe try one of the links below or a search?', 'response' ); ?></p>
	
					<?php get_search_form(); ?>
	
					<?php the_widget( 'WP_Widget_Recent_Posts' ); ?>
	
					<div class="widget">
						<h2 class="widgettitle"><?php _e( 'Most Used Categories', 'response' ); ?></h2>
						<ul>
						<?php wp_list_categories( array( 'orderby' => 'count', 'order' => 'DESC', 'show_count' => 1, 'title_li' => '', 'number' => 10 ) ); ?>
						</ul>
					</div>
	
					<?php
					/* translators: %1$s: smilie */
					$archive_content = '<p>' . sprintf( __( 'Try looking in the monthly archives. %1$s', 'response' ), convert_smilies( ':)' ) ) . '</p>';
					the_widget( 'WP_Widget_Archives', 'dropdown=1', "after_title=</h2>$archive_content" );
					?>
	
					<?php the_widget( 'WP_Widget_Tag_Cloud' ); ?>
	
				</div><!-- .entry-content -->
			</article><!-- #post-0 -->
			
			<?php do_action( 'response_after_content'); ?>
			
		</div><!-- #content .span12-->
		
	</div><!-- .row-fluid-->
</div><!-- #container .fluid-container-->

<?php do_action( 'response_after_container'); ?>

<?php get_footer(); ?>