<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
get_header(); ?>

<?php do_action( 'response_before_container'); ?>

<div id="container" <?php response_filter_container_class(); ?>>
	
	<?php do_action( 'response_before_content_container'); ?>
	
	<div id="content" <?php response_filter_content_class(); ?>>
			
		<?php do_action( 'response_before_content'); ?>

		<article id="post-0" class="post error404 not-found">
			<header class="entry-header">
				<h2 class="entry-title"><?php _e( 'Oops! That page can&rsquo;t be found.', 'response' ); ?></h2>
			</header>

			<div class="entry-content">
				<p><?php _e( 'It looks like nothing was found at this location. Maybe try searching for it?', 'response' ); ?></p>
				
				<?php get_search_form(); ?>

			</div><!-- .entry-content -->
		</article><!-- #post-0 -->
		
		<?php do_action( 'response_after_content'); ?>
		
	</div><!-- #content -->
	
	<?php do_action( 'response_after_content_container'); ?>
	
</div><!-- #container .row-fluid-->

<?php do_action( 'response_after_container'); ?>

<?php get_footer(); ?>