<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since	 1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
do_action('response_before_footer_container'); ?>

<footer class="site-footer container-fluid">
	
	<?php do_action('response_before_footer_widgets'); ?>
	<div id="footer-widgets" class="row-fluid">
		<?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar('response_footer_widgets')) : ?>
			<?php //TODO: INSERT DEFAULT WIDGETS ?>
		<?php endif; ?>
	</div><!-- .footer-widgets .row-fluid -->
	<?php do_action('response_after_footer_widgets'); ?>
	
	
	<?php do_action('response_before_site_info'); ?>
	<div class="site-info row-fluid">
		<?php do_action( 'response_site_info' ); ?>
	</div><!-- .site-info .row-fluid -->
	<?php do_action('response_after_site_info'); ?>
	
</footer><!-- .site-footer .container-fluid -->

<?php do_action('response_after_footer_container'); ?>
	
<?php wp_footer(); ?>

</body>
</html>