<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
do_action('response_before_footer_widgets'); ?>

<div id="footer-widgets" class="row-fluid">
	<?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar('response-footer-widgets')) : ?>
		<?php //TODO: INSERT DEFAULT WIDGETS ?>
	<?php endif; ?>
</div><!-- #footer-widgets .row-fluid  -->

<?php do_action('response_after_footer_widgets'); ?>
	

<?php do_action('response_before_footer_container'); ?>

<footer class="site-footer row-fluid">
	
	<?php do_action('response_before_footer'); ?>
	
	<?php do_action('response_before_site_info'); ?>
	<div class="site-info">
		<?php do_action( 'response_site_info' ); ?>
	</div><!-- .site-info -->
	<?php do_action('response_after_site_info'); ?>
	
	<?php do_action('response_after_footer'); ?>
	
</footer><!-- .site-footer .row-fluid -->

<?php do_action('response_after_footer_container'); ?>


</div><!-- #wrapper .container-fluid -->

<?php do_action('response_after_wrapper'); ?>

<?php wp_footer(); ?>

</body>
</html>