<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since	 1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// TODO: Fix documentation
// Load Core
require_once( get_template_directory() . '/core/init.php' );

// TODO: Fix documentation
// Enqueue core scripts and core styles
function response_scripts() {
	global $post;

	wp_enqueue_style( 'theme-styles', get_stylesheet_directory_uri() . '/inc/css/theme.css', array('style'), '1.0' );	
}
add_action( 'wp_enqueue_scripts', 'response_scripts', 20 );

// Theme specific functions will go here. This should be very limited