<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since	 1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
get_header(); ?>

<?php do_action( 'response_before_container'); ?>

<div id="container" class="container-fluid">
	<div class="row-fluid">
		
		<div id="content" class="span9">
			
			<?php do_action( 'response_before_content'); ?>
			
			<?php if ( have_posts() ) : ?>

				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'content', get_post_format() ); ?>
					
				<?php endwhile; ?>

			<?php elseif ( current_user_can( 'edit_posts' ) ) : ?>
	
				<?php get_template_part( 'no-results', 'index' ); ?>
	
			<?php endif; ?>
			
			<?php do_action( 'response_after_content'); ?>
			
		</div><!-- #content .span9-->
		
		<?php get_sidebar(); ?>
		
	</div><!-- .row-fluid-->
</div><!-- #container .fluid-container-->

<?php do_action( 'response_after_container'); ?>

<?php get_footer(); ?>