<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
get_header(); ?>

<?php

// TODO: Move to hooks
function callout_section_action() {
	do_action('response_callout');
}
add_action('callout_section', 'callout_section_action');

function twitterbar_section_action() {
	do_action('response_twitter_bar');
}
add_action('twitterbar_section', 'twitterbar_section_action');

function breadcrumbs_section_action() {
	do_action('response_breadcrumbs');
}
add_action('breadcrumbs', 'breadcrumbs_section_action');

function page_section_order_action() {
	global $post;
	
	$page_section_order = get_post_meta($post->ID, 'response_page_section_order' , true);

	// TODO: Remove debugging
	//var_dump($page_section_order);
	if ( is_array($page_section_order) ) {
		foreach ( $page_section_order as $func) {
			do_action($func);
		}
	}
}
add_action('response_before_container', 'page_section_order_action');

?>
<?php do_action( 'response_before_container'); ?>

<div id="container" <?php response_filter_container_class(); ?>>
	
	<?php do_action( 'response_before_content_container'); ?>
	
	<div id="content" <?php response_filter_content_class(); ?>>
		
		<?php do_action( 'response_before_content'); ?>
		
		<?php while ( have_posts() ) : the_post(); ?>

			<?php get_template_part( 'content', 'page' ); ?>

			<?php comments_template( '', true ); ?>

		<?php endwhile; // end of the loop. ?>
	
		<?php do_action( 'response_after_content'); ?>
		
	</div><!-- #content -->
	
	<?php do_action( 'response_after_content_container'); ?>
		
</div><!-- #container .row-fluid-->

<?php do_action( 'response_after_container'); ?>

<?php get_footer(); ?>