<?php
/**
 * TODO: Edit Title Content
 *
 * TODO: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme. TODO: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since	 1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>

<div id="secondary" class="widget-area span3">
	
	<?php do_action( 'response_before_sidebar' ); ?>
	
	<div id="sidebar" class="container-fluid">
	<?php if ( ! dynamic_sidebar( 'sidebar' ) ) : ?>

		<?php //TODO: ADD DEFAULT SIDEBAR INFO ?>
		
	<?php endif; ?>
	</div><!-- #sidebar .container-fluid -->
	
	<?php do_action( 'response_after_sidebar' ); ?>
	
</div><!-- #secondary .widget-area .span3 -->