<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Response core framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Response
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
get_header(); ?>

<?php do_action( 'response_before_container'); ?>

<div id="container" class="row-fluid">
	
	<div id="content" class="span9">
		
		<?php do_action( 'response_before_content'); ?>
		
		<?php while ( have_posts() ) : the_post(); ?>

			<?php get_template_part( 'content', 'single' ); ?>

			<?php
				// If comments are open or we have at least one comment, load up the comment template
				if ( comments_open() || '0' != get_comments_number() )
					comments_template( '', true );
			?>

		<?php endwhile; // end of the loop. ?>
	
		<?php do_action( 'response_after_content'); ?>
		
	</div><!-- #content .span9-->
	
	<?php get_sidebar(); ?>
		
</div><!-- #container .row-fluid-->

<?php do_action( 'response_after_container'); ?>

<?php get_footer(); ?>