<?php
/**
 * Title: update.php
 *
 * Description: Notify user of theme update on "Updates" page in Dashboard.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
/*
TEMP: Enable update check on every request. Normally you don't need this! This is for testing only!
set_site_transient('update_themes', null);
*/

add_filter('pre_set_site_transient_update_themes', 'cyberchimps_check_for_update');

if(function_exists('wp_get_theme')){
    $theme_data = wp_get_theme(get_option('template'));
    $theme_version = $theme_data->Version;
} else {
    $theme_data = get_theme_data( get_template_directory() . '/style.css');
    $theme_version = $theme_data['Version'];
}
$theme_base = get_option('template');

/******************Change this*******************/
$api_url = 'http://cyberchimps.com/api/';
/************************************************/
	
function cyberchimps_check_for_update($checked_data) 
{
	global $wp_version, $theme_version, $theme_base, $api_url;
	
	$request = array(
		'slug' => $theme_base,
		'version' => $theme_version 
	);
        // Start checking for an update
	$send_for_check = array(
		'body' => array(
			'action' => 'theme_update', 
			'request' => serialize($request),
			'api-key' => md5(home_url())
		),
		'user-agent' => 'WordPress/' . $wp_version . '; ' . home_url()
	);

	$raw_response = wp_remote_post($api_url, $send_for_check);

	if (!is_wp_error($raw_response) && ($raw_response['response']['code'] == 200))
	{
    $response = unserialize($raw_response['body']);
	}

	// Feed the update data into WP updater
	if (!empty($response)) 
	{
		$checked_data->response[$theme_base] = $response;
	}

	return $checked_data;
}

if (is_admin())
{
	$current = get_transient('update_themes');
}